version: "3.9"

services:
  web:
    image: ghcr.io/arcky97/arcky-tech-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3090:3090"

  docs:
    image: ghcr.io/arcky97/arcky-tech-docs:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3091:3090"

  # later
  # dashboard:
  #   image: ghcr.io/arcky97/arcky-tech-dashboard:latest
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:3092:3090"